parameters:
    images_directory: '%kernel.root_dir%/../web/uploads/images'

services:
    app.image_uploader:
        class: AppBundle\Services\FileUploader
        arguments: ['%images_directory%']
